// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafESpt0TNpxUhpnpuLbN8VxQX7l1APOM',
    appId: '1:145025515885:web:64fa38170f88f6e53cda64',
    messagingSenderId: '145025515885',
    projectId: 'ecommerceapp-e2323',
    authDomain: 'ecommerceapp-e2323.firebaseapp.com',
    storageBucket: 'ecommerceapp-e2323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPfJn8_UnMBiY4wcX3kuo7kp-KRMfJug',
    appId: '1:145025515885:android:54f5016011ec344e3cda64',
    messagingSenderId: '145025515885',
    projectId: 'ecommerceapp-e2323',
    storageBucket: 'ecommerceapp-e2323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrw0lRE_fM-yo713SeDR2cu4CLpUTXJxY',
    appId: '1:145025515885:ios:a9eb45e0d7678d553cda64',
    messagingSenderId: '145025515885',
    projectId: 'ecommerceapp-e2323',
    storageBucket: 'ecommerceapp-e2323.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpj6fjsobnxtINt9ifap2MYO6Rc1Wf0FE',
    appId: '1:768140632617:ios:67e94e1cd6da3127a4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    storageBucket: 'support-training-app.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCafESpt0TNpxUhpnpuLbN8VxQX7l1APOM',
    appId: '1:145025515885:web:1788a392a53e481d3cda64',
    messagingSenderId: '145025515885',
    projectId: 'ecommerceapp-e2323',
    authDomain: 'ecommerceapp-e2323.firebaseapp.com',
    storageBucket: 'ecommerceapp-e2323.appspot.com',
  );

}