// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHhKuFl_16G88n93AR_O2d1HRa9Rd9j3U',
    appId: '1:768140632617:web:d1b1af8bc4a67e34a4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    authDomain: 'support-training-app.firebaseapp.com',
    storageBucket: 'support-training-app.appspot.com',
    measurementId: 'G-R46GYZRS5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqIGcHXE_ynLyrd8gEo3ttP2Em9qvgQ8',
    appId: '1:768140632617:android:c735cccf0beb8be3a4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    storageBucket: 'support-training-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpj6fjsobnxtINt9ifap2MYO6Rc1Wf0FE',
    appId: '1:768140632617:ios:67e94e1cd6da3127a4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    storageBucket: 'support-training-app.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpj6fjsobnxtINt9ifap2MYO6Rc1Wf0FE',
    appId: '1:768140632617:ios:67e94e1cd6da3127a4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    storageBucket: 'support-training-app.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHhKuFl_16G88n93AR_O2d1HRa9Rd9j3U',
    appId: '1:768140632617:web:611dbdf8219cb53ea4f238',
    messagingSenderId: '768140632617',
    projectId: 'support-training-app',
    authDomain: 'support-training-app.firebaseapp.com',
    storageBucket: 'support-training-app.appspot.com',
    measurementId: 'G-D77XZZZ2EY',
  );
}
